/**
 * What the workspace looks like before anybody has changed anything.
 *
 * Beside the shapes rather than in the store, because a leaf that wants the
 * app's own answer for its section can read this without importing the
 * module that normalises it. The store reads it, the normaliser falls back
 * to it, and neither of them owns it.
 */
import { DEFAULT_AMBIENT_METRES } from "../ambientScreen";
import { DEFAULT_APPROACH } from "../approach";
import { DEFAULT_CUBE_LEVEL } from "../cappi";
import { DEFAULT_LIGHTNING_RULE } from "../lightningWatch";
import { DEFAULT_LOOP_VOLUMES } from "../siteLoop";
import { DEFAULT_QUIET_HOURS } from "../watch";
import { SCHEMA_VERSION, type AppSettings } from "./types";

export const DEFAULT_SETTINGS: AppSettings = {
  schemaVersion: SCHEMA_VERSION,
  theme: "dark",
  workspaceTheme: null,
  ambient: false,
  almanac: true,
  occasions: { enabled: true, declined: {}, seen: {} },
  language: "en",
  units: "imperial",
  unitsChosen: false,
  clock: "local",
  textScale: 100,
  projection: "mercator",
  mapStyle: "auto",
  camera: {
    center: [-85.5, 25.5],
    zoom: 4.55,
    bearing: 0,
    pitch: 0,
  },
  radar: {
    enabled: true,
    opacity: 0.7,
    animationSpeed: -0.1,
    loopMinutes: 120,
    futureRadar: false,
    singleSite: true,
    loopVolumes: DEFAULT_LOOP_VOLUMES,
    dealias: true,
    live: false,
    persistence: false,
    smoothSweep: false,
    smoothGrids: false,
    stormMotion: null,
    station: null,
    product: "reflectivity",
    classificationProduct: "HHC",
    tilt: 0,
    thresholds: {},
  },
  layers: {
    weatherAlerts: true,
    spcOutlooks: false,
    wpcExcessiveRain: false,
    wpcWinterSeverity: false,
    spcDiscussions: false,
    stormReports: false,
    stormCells: false,
    classification: false,
    probSevere: false,
    earthquakes: false,
    wildfires: false,
    smoke: false,
    forecastSmoke: false,
    metar: false,
    riverGauges: false,
    buoys: false,
    aviation: false,
    tropical: true,
    satellite: false,
    customOverlay: false,
    rotationTracks: false,
    azShear: false,
    hail: false,
    hailSwath: false,
    vilDensity: false,
    shi: false,
    posh: false,
    vii: false,
    echoTops: false,
    vil: false,
    precipRate: false,
    qpeHour: false,
    qpeDay: false,
    counties: false,
    night: false,
    gaugeQpe: false,
    ffgHour: false,
    ffgThreeHour: false,
    unitStreamflow: false,
    precipType: false,
    snowfall: false,
    lightningDensity: false,
    lightningForecast: false,
    lightningJump: false,
    isothermReflectivity: false,
    cappi: false,
    lightningFlashes: false,
    wind: false,
    surge: false,
  },
  palettes: [],
  paletteAssignments: {},
  surgeCategory: 3,
  snowfallWindow: "24h",
  alertTypes: {},
  overlayOpacity: {},
  overlayOrder: [],
  watchPlaces: [],
  watch: {
    enabled: false,
    center: [-96.8, 32.78],
    radiusMiles: 30,
    sound: false,
    voice: false,
    minSeverity: "severe",
    quietHours: DEFAULT_QUIET_HOURS,
  },
  followNewWarnings: false,
  watchRings: false,
  ambientMetres: DEFAULT_AMBIENT_METRES,
  satelliteBand: "geocolor",
  approach: DEFAULT_APPROACH,
  lightningWatch: DEFAULT_LIGHTNING_RULE,
  wpcDay: 1,
  spcDay: 1,
  spcHazard: "categorical",
  wssiDay: 1,
  gaugeQpePeriod: "24h",
  rotationPeriod: "1h",
  lightningWindow: "5m",
  lightningForecastWindow: "30m",
  lightningJumpWindow: "max",
  isothermLevel: "minus10",
  azShearLevel: "low",
  cappiField: "reflectivity",
  cappiLevel: DEFAULT_CUBE_LEVEL,
  presets: [null, null, null, null],
  incidentPacks: {
    diskLimitMb: 4096,
    selectedId: null,
    references: [],
  },
  seenWelcome: false,
  seenReveal: false,
  calm: false,
  ambientIdleMinutes: 0,
  displayAwake: false,
  exportKeys: false,
  wallpaperMinutes: 0,
  tray: true,
  closeToTray: false,
  glanceOnTop: false,
  calmBorrowed: {},
  alertVolume: 0.18,
  alertSoundPath: null,
  journal: true,
  catchUp: true,
  curiosities: true,
  curiositiesFound: [],
  lastSeen: 0,
};
