import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    // The build scripts are plain modules with their own tests, and a parser
    // the shipped data is generated by is worth covering.
    include: ["src/**/*.test.{ts,tsx}", "scripts/**/*.test.mjs"],
    // A bound, because the default five seconds was the only one on a suite
    // that reaches into jsdom and a stubbed IndexedDB. A test that hangs
    // there hangs the whole run rather than failing.
    testTimeout: 10_000,
    hookTimeout: 10_000,
    coverage: {
      reporter: ["text", "html"],
      // Collected and never enforced, which is a number nobody has to keep.
      // The floor is today's, rounded down: it is here to catch a whole area
      // going untested, not to be nudged up a point at a time.
      thresholds: {
        // Today's numbers rounded down, measured rather than guessed:
        // statements 79.9, branches 70.4, functions 73.9, lines 81.7. The
        // floor is here to catch a whole area going untested, not to be
        // nudged up a point at a time.
        statements: 78,
        branches: 69,
        functions: 72,
        lines: 80,
      },
    },
  },
});
