import { describe, expect, it } from "vitest";
import {
  allowanceIn,
  askedFor,
  batchBody,
  cratesIn,
  hits,
  spellings,
  unmetNeeds,
  verdict,
} from "./advisories-lib.mjs";

/**
 * The gate that catches an advisory `cargo audit` cannot see.
 *
 * Every way it can go wrong looks like a clean tree: a lock it stops parsing,
 * a spelling it stops asking about, an allowance that swallows something
 * nobody read. So each of those is a test rather than a comment.
 */

describe("reading the lock", () => {
  it("takes the name and version of every package", () => {
    const lock = [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "block-buffer"',
      'version = "0.10.4"',
      'source = "registry+https://github.com/rust-lang/crates.io-index"',
      "",
      "[[package]]",
      'name = "sha2"',
      'version = "0.10.9"',
      "dependencies = [",
      ' "block-buffer",',
      "]",
      "",
    ].join("\n");
    expect(cratesIn(lock)).toEqual([
      { name: "block-buffer", version: "0.10.4" },
      { name: "sha2", version: "0.10.9" },
    ]);
  });

  it("does not read the lock's own format version as a package", () => {
    // `version = 4` sits at the top of a v4 lock with no package above it,
    // and reading it as one would ask an advisory database about whatever
    // name happened to be left over from the file before.
    const lock = [
      'version = "4"',
      "",
      "[[package]]",
      'name = "only"',
      'version = "1.0.0"',
    ].join("\n");
    expect(cratesIn(lock)).toEqual([{ name: "only", version: "1.0.0" }]);
  });

  it("does not carry a name past the package it belongs to", () => {
    // A package with no version of its own must not take the next one's. The
    // first version of this gave the second package a name too, so that name
    // overwrote the first and the reset at `[[package]]` was never needed:
    // taking the reset out left every test in this file green. The second
    // package here has no name of its own, which is the only shape that needs
    // it.
    const lock = [
      "[[package]]",
      'name = "first"',
      "",
      "[[package]]",
      'version = "2.0.0"',
      "",
      "[[package]]",
      'name = "third"',
      'version = "3.0.0"',
    ].join("\n");
    expect(cratesIn(lock)).toEqual([{ name: "third", version: "3.0.0" }]);
  });
});

describe("which names get asked about", () => {
  it("asks under both spellings, because the databases disagree with crates.io", () => {
    // The whole reason this gate exists. GHSA-qwgh-2vcv-g2f7 answers to
    // `block_buffer` and says nothing to `block-buffer`, which is how three
    // scanners reported this tree clean.
    expect(spellings("block-buffer")).toEqual(["block-buffer", "block_buffer"]);
    expect(spellings("block_buffer")).toEqual(["block_buffer", "block-buffer"]);
  });

  it("asks once about a name that cannot be spelled two ways", () => {
    expect(spellings("sha2")).toEqual(["sha2"]);
  });

  it("keeps the questions and the answers in step", () => {
    const asked = askedFor([
      { name: "block-buffer", version: "0.10.4" },
      { name: "sha2", version: "0.10.9" },
    ]);
    expect(asked).toEqual([
      { crate: "block-buffer", version: "0.10.4", spelling: "block-buffer" },
      { crate: "block-buffer", version: "0.10.4", spelling: "block_buffer" },
      { crate: "sha2", version: "0.10.9", spelling: "sha2" },
    ]);
    expect(batchBody(asked).queries[1]).toEqual({
      package: { ecosystem: "crates.io", name: "block_buffer" },
      version: "0.10.4",
    });
  });
});

describe("what the answers mean", () => {
  const asked = askedFor([
    { name: "block-buffer", version: "0.10.4" },
    { name: "sha2", version: "0.10.9" },
  ]);

  it("finds an advisory that only the other spelling answers to", () => {
    // Only an identifier comes back from a batch: `querybatch` answers with
    // that and a modified time, and nothing else. The reply here carries a
    // summary the way a real one does not, so the reading cannot come to
    // depend on a field the service does not send.
    const found = hits(asked, [
      {},
      { vulns: [{ id: "GHSA-qwgh-2vcv-g2f7", summary: "cursor corruption" }] },
      {},
    ]);
    expect(found).toEqual([
      {
        crate: "block-buffer",
        version: "0.10.4",
        spelling: "block_buffer",
        id: "GHSA-qwgh-2vcv-g2f7",
      },
    ]);
  });

  it("reports one advisory once when both spellings answer to it", () => {
    const found = hits(asked, [
      { vulns: [{ id: "GHSA-one" }] },
      { vulns: [{ id: "GHSA-one" }] },
      {},
    ]);
    expect(found.map((one) => one.id)).toEqual(["GHSA-one"]);
  });

  it("says nothing about a tree with nothing in it", () => {
    expect(hits(asked, [{}, {}, {}])).toEqual([]);
    expect(hits(asked, [null, undefined, {}])).toEqual([]);
  });
});

describe("the allowance", () => {
  it("takes an identifier that has its reasoning written above it", () => {
    const { allowed, unexplained } = allowanceIn(
      [
        "# Not reachable here: it needs a panic caught inside a hash update.",
        "# Look again by 2027-03-01.",
        "GHSA-qwgh-2vcv-g2f7",
      ].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-qwgh-2vcv-g2f7"]);
    expect(allowed.get("GHSA-qwgh-2vcv-g2f7").reason).toContain("2027-03-01");
    expect(unexplained).toEqual([]);
  });

  it("refuses one written on its own, because that is a silenced alarm", () => {
    const { allowed, unexplained } = allowanceIn(
      ["# A real reason.", "GHSA-explained", "", "GHSA-bare"].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-explained"]);
    expect(unexplained).toEqual(["GHSA-bare"]);
  });

  it("does not let one reason cover the identifier after it", () => {
    // A blank line ends a reason. Without that, adding an identifier to the
    // bottom of the file inherits whatever argument was made last.
    const { allowed, unexplained } = allowanceIn(
      ["# The reason for the first.", "GHSA-first", "GHSA-second"].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-first"]);
    expect(unexplained).toEqual(["GHSA-second"]);
  });
});

describe("what an allowance rests on", () => {
  it("reads the crates named after the identifier", () => {
    const { allowed } = allowanceIn(
      ["# Fixed by moving our own hashing.", "GHSA-one needs sha2 0.11"].join(
        "\n",
      ),
    );
    expect(allowed.get("GHSA-one").needs).toEqual([
      { crate: "sha2", version: "0.11" },
    ]);
  });

  it("matches a version as a prefix, so a patch is the same claim", () => {
    const crates = [{ name: "sha2", version: "0.11.4" }];
    expect(unmetNeeds([{ crate: "sha2", version: "0.11" }], crates)).toEqual(
      [],
    );
    expect(
      unmetNeeds([{ crate: "sha2", version: "0.12" }], crates),
    ).toHaveLength(1);
    expect(unmetNeeds([{ crate: "gone", version: "" }], crates)).toHaveLength(
      1,
    );
  });

  it("stands an allowance down when what it rests on has gone", () => {
    // The failure this exists for. An advisory allowed for on the strength of
    // a fix stays allowed for after the fix is reverted, because its own
    // identifier, crate and version have not moved: what moved is the tree
    // around it. Putting this app's hashing back on sha2 0.10 restored the
    // reachable position the entry says was fixed, and the run stayed green.
    const found = [
      { crate: "block-buffer", id: "GHSA-one", version: "0.10.4" },
    ];
    const allowed = new Map([
      [
        "GHSA-one",
        {
          reason: "we moved off it",
          needs: [{ crate: "sha2", version: "0.11" }],
        },
      ],
    ]);
    const held = verdict(found, allowed, [{ name: "sha2", version: "0.11.0" }]);
    expect(held.unexplained).toEqual([]);
    const gone = verdict(found, allowed, [{ name: "sha2", version: "0.10.9" }]);
    expect(gone.unexplained.map((one) => one.id)).toEqual(["GHSA-one"]);
    expect([...gone.voided.keys()]).toEqual(["GHSA-one"]);
  });
});

describe("the verdict", () => {
  const found = [
    { crate: "block-buffer", id: "GHSA-known", version: "0.10.4" },
    { crate: "lru", id: "GHSA-new", version: "0.12.0" },
  ];

  it("fails on an advisory nobody has written a reason for", () => {
    const { unexplained, explained } = verdict(
      found,
      new Map([["GHSA-known", { reason: "why" }]]),
    );
    expect(unexplained.map((one) => one.id)).toEqual(["GHSA-new"]);
    expect(explained.map((one) => one.id)).toEqual(["GHSA-known"]);
  });

  it("passes once every one of them is accounted for", () => {
    const { unexplained } = verdict(
      found,
      new Map([
        ["GHSA-known", { reason: "why" }],
        ["GHSA-new", { reason: "why" }],
      ]),
    );
    expect(unexplained).toEqual([]);
  });

  it("names an allowance whose advisory has left the tree", () => {
    // The file's own key. A reason nobody re-reads is how an allowance list
    // becomes a list of things that stopped applying years ago.
    const { stale } = verdict(
      found,
      new Map([
        ["GHSA-known", { reason: "why" }],
        ["GHSA-new", { reason: "why" }],
        ["GHSA-gone", { reason: "for a crate that was removed" }],
      ]),
    );
    expect(stale).toEqual(["GHSA-gone"]);
  });
});
