import { describe, expect, it } from "vitest";
import {
  allowanceIn,
  askedFor,
  batchBody,
  cratesIn,
  hits,
  spellings,
  verdict,
} from "./advisories-lib.mjs";

/**
 * The gate that catches an advisory `cargo audit` cannot see.
 *
 * Every way it can go wrong looks like a clean tree: a lock it stops parsing,
 * a spelling it stops asking about, an allowance that swallows something
 * nobody read. So each of those is a test rather than a comment.
 */

describe("reading the lock", () => {
  it("takes the name and version of every package", () => {
    const lock = [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "block-buffer"',
      'version = "0.10.4"',
      'source = "registry+https://github.com/rust-lang/crates.io-index"',
      "",
      "[[package]]",
      'name = "sha2"',
      'version = "0.10.9"',
      "dependencies = [",
      ' "block-buffer",',
      "]",
      "",
    ].join("\n");
    expect(cratesIn(lock)).toEqual([
      { name: "block-buffer", version: "0.10.4" },
      { name: "sha2", version: "0.10.9" },
    ]);
  });

  it("does not read the lock's own format version as a package", () => {
    // `version = 4` sits at the top of a v4 lock with no package above it,
    // and reading it as one would ask an advisory database about whatever
    // name happened to be left over from the file before.
    const lock = ['version = "4"', "", "[[package]]", 'name = "only"', 'version = "1.0.0"'].join(
      "\n",
    );
    expect(cratesIn(lock)).toEqual([{ name: "only", version: "1.0.0" }]);
  });

  it("does not carry a name past the package it belongs to", () => {
    // A package with no version of its own must not take the next one's.
    const lock = [
      "[[package]]",
      'name = "first"',
      "",
      "[[package]]",
      'name = "second"',
      'version = "2.0.0"',
    ].join("\n");
    expect(cratesIn(lock)).toEqual([{ name: "second", version: "2.0.0" }]);
  });
});

describe("which names get asked about", () => {
  it("asks under both spellings, because the databases disagree with crates.io", () => {
    // The whole reason this gate exists. GHSA-qwgh-2vcv-g2f7 answers to
    // `block_buffer` and says nothing to `block-buffer`, which is how three
    // scanners reported this tree clean.
    expect(spellings("block-buffer")).toEqual(["block-buffer", "block_buffer"]);
    expect(spellings("block_buffer")).toEqual(["block_buffer", "block-buffer"]);
  });

  it("asks once about a name that cannot be spelled two ways", () => {
    expect(spellings("sha2")).toEqual(["sha2"]);
  });

  it("keeps the questions and the answers in step", () => {
    const asked = askedFor([
      { name: "block-buffer", version: "0.10.4" },
      { name: "sha2", version: "0.10.9" },
    ]);
    expect(asked).toEqual([
      { crate: "block-buffer", version: "0.10.4", spelling: "block-buffer" },
      { crate: "block-buffer", version: "0.10.4", spelling: "block_buffer" },
      { crate: "sha2", version: "0.10.9", spelling: "sha2" },
    ]);
    expect(batchBody(asked).queries[1]).toEqual({
      package: { ecosystem: "crates.io", name: "block_buffer" },
      version: "0.10.4",
    });
  });
});

describe("what the answers mean", () => {
  const asked = askedFor([
    { name: "block-buffer", version: "0.10.4" },
    { name: "sha2", version: "0.10.9" },
  ]);

  it("finds an advisory that only the other spelling answers to", () => {
    const found = hits(asked, [
      {},
      { vulns: [{ id: "GHSA-qwgh-2vcv-g2f7", summary: "cursor corruption" }] },
      {},
    ]);
    expect(found).toEqual([
      {
        crate: "block-buffer",
        version: "0.10.4",
        spelling: "block_buffer",
        id: "GHSA-qwgh-2vcv-g2f7",
        summary: "cursor corruption",
      },
    ]);
  });

  it("reports one advisory once when both spellings answer to it", () => {
    const found = hits(asked, [
      { vulns: [{ id: "GHSA-one" }] },
      { vulns: [{ id: "GHSA-one" }] },
      {},
    ]);
    expect(found.map((one) => one.id)).toEqual(["GHSA-one"]);
  });

  it("says nothing about a tree with nothing in it", () => {
    expect(hits(asked, [{}, {}, {}])).toEqual([]);
    expect(hits(asked, [null, undefined, {}])).toEqual([]);
  });
});

describe("the allowance", () => {
  it("takes an identifier that has its reasoning written above it", () => {
    const { allowed, unexplained } = allowanceIn(
      [
        "# Not reachable here: it needs a panic caught inside a hash update.",
        "# Look again by 2027-03-01.",
        "GHSA-qwgh-2vcv-g2f7",
      ].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-qwgh-2vcv-g2f7"]);
    expect(allowed.get("GHSA-qwgh-2vcv-g2f7")).toContain("2027-03-01");
    expect(unexplained).toEqual([]);
  });

  it("refuses one written on its own, because that is a silenced alarm", () => {
    const { allowed, unexplained } = allowanceIn(
      ["# A real reason.", "GHSA-explained", "", "GHSA-bare"].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-explained"]);
    expect(unexplained).toEqual(["GHSA-bare"]);
  });

  it("does not let one reason cover the identifier after it", () => {
    // A blank line ends a reason. Without that, adding an identifier to the
    // bottom of the file inherits whatever argument was made last.
    const { allowed, unexplained } = allowanceIn(
      ["# The reason for the first.", "GHSA-first", "GHSA-second"].join("\n"),
    );
    expect([...allowed.keys()]).toEqual(["GHSA-first"]);
    expect(unexplained).toEqual(["GHSA-second"]);
  });
});

describe("the verdict", () => {
  const found = [
    { crate: "block-buffer", id: "GHSA-known", version: "0.10.4" },
    { crate: "lru", id: "GHSA-new", version: "0.12.0" },
  ];

  it("fails on an advisory nobody has written a reason for", () => {
    const { unexplained, explained } = verdict(
      found,
      new Map([["GHSA-known", "why"]]),
    );
    expect(unexplained.map((one) => one.id)).toEqual(["GHSA-new"]);
    expect(explained.map((one) => one.id)).toEqual(["GHSA-known"]);
  });

  it("passes once every one of them is accounted for", () => {
    const { unexplained } = verdict(
      found,
      new Map([
        ["GHSA-known", "why"],
        ["GHSA-new", "why"],
      ]),
    );
    expect(unexplained).toEqual([]);
  });

  it("names an allowance whose advisory has left the tree", () => {
    // The file's own key. A reason nobody re-reads is how an allowance list
    // becomes a list of things that stopped applying years ago.
    const { stale } = verdict(
      found,
      new Map([
        ["GHSA-known", "why"],
        ["GHSA-new", "why"],
        ["GHSA-gone", "for a crate that was removed"],
      ]),
    );
    expect(stale).toEqual(["GHSA-gone"]);
  });
});
